language: node_js
node_js:
- '4'

env:
- CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
- npm install -g grunt-cli

deploy:
  provider: heroku
  api_key:
    secure: zjnQwdehSBPLEbFFJ74eVQRAE7pJe0h2E0uHBaBd31L4Heah7u0QHK5ikkSVFfFc8Ds+jVdTbkdTmnQrsn0jk8T3kJdc//sNgk+jzU8JjIcqVKXGGi/iIbyyzR6SvzueMj1Aup+xUXAqEa1bh6jH8XXiPxcxttCB47CkyiWJILstwJrRn38whnQ2e3nl6yax+0L+zIwQNlGn4f8yP94qcK6+WFRQZbZJqMJ2+WzvO6QOgmUUq3iLTjfJpvv8gi7ihg2Fae8yjvVCxZJaiN2A5ekDKs85Qy5bIjggNddRWBnagVqrpCgdQMqLy7yZdC/3PG9MJ+zrmOg4Ic1w4ygj3Mrgg/P1720v7NG0oFiwBFUpg5pZmjWHAco5izVQIv4ztY3C64cTPUa8Zg7LkfctK+3lS2Y+n3cYGMXDguiwvTVEOv5kgsK7CbD4Z7du05yRrHWkayagZKXwOmgXK2MNj0hi0X2pu0wHD4yBs8mCgsXdMgSBtYsxRNbrckAZi2/F+qfURq3SzHwn9WphwXC4EWF9S5E3WL9h63KKlP6Jz82Lss5HxhljhgG3Uvc54dRJbc2e7Hegp09qySDnl+TObLB8W3q++TJ3dSKrP3OVSyRZZVzf4rpG88yO3oLOkvhYCt2KabD0xNhVBZbuGpuwCcTSEW4yC3vf0ZxiK6tQfMA=
  app:
    master: insights-web-data-connector
