language: node_js
node_js:
  - '0.12'

before_install:
  - npm install -g grunt-cli

deploy:
  provider: heroku
  api_key:
    secure: XIb2akqVREhdZcLRHy+q02ISCLsaj7z1gft8bOjo002qhO0vqppjPI8fKBTCWm+eEox74ILpHzsGBgB8K4J4qiQInVcykUf2+8mKNj4iUbvXtf4un134WcM8jcNCfUUlSOT+J6rChogK6q4DXJzOJ/DEiFA7eWlh/UpVC0FHHqaHTf7fLEi/wHVR/YFVxG9IEAAghd4sdHcu+sd1T1exiRbFVzR70ga9LyDHIzRYvRZhnJ1/oGPS57a96g2yimpgGEo06/BCIRXLpq4+x553o515TZ0z64dE9NJKNq2z1tZEsCVXgsTJaIG5WSzq+i6wtqPBI/9D4DOq8DIYesp2Z3WlFtFoddBPQdnYlsf44Cg85Twibw84ughvtzbh2q67TDErgReqwuZf2yQ4fIEuqwzNKwGdwSz1uSRxj26H1blu07WEwN13uSwmZv3cK8+p2i4xJgqBsRtL32oKOGep+OQdOWtNTie7E9VYyLsmeSxxqSqmI0vZ6umkPwnkbT8Mqd37fjS/2RflfOOuBJ8udU37zZHq7FANeu1f3adIuqmg8iBkFKLPGZbSZhzl0iTr1I3rmzFiYGcE01XiI7LN+FLFqZUuarRm/I9uwPskAGJvtemgm+AD5ECWX+VWvTzlet5HtX0MsemirZWYtv83yWDHa0Y6Av5EPhpZxviRVR0=
  app:
    master: insights-web-data-connector
